stages:          
  - build
  - test

build-job:      
  stage: build
  script:
    - cd client
    - npm run build

lint-test-job:  
  stage: test    
  script:
    - cd client
    - npm run lint

format-test-job:
  stage: test
  script:
    - npm run format