export { Home } from "./Home";
export { Login } from "./Login";
export { Register } from "./Register";
export { AboutGame } from "./AboutGame";
export { IcebreakerForm } from "./IceBreakerForm";
export { Profile } from "./Profile";
export { InCategory } from "./Category";
export { Categories } from "./CategoryPage";
export { AdminPage } from "./AdminPage";
